import React from 'react'
import './PrivacyPolicy.css'

const PrivacyPolicy = () => {
  return (
    <div className="PrivacyPolicy">
        <div className="privacy-content">
            <h1>Privacy Policy</h1>

            <h2> Interpretation and Definitions</h2>

            <h2>Interpretation</h2>

            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h2>Definitions</h2>

            <p>For the purposes of this Privacy Policy:</p>

            <ul>
              <li><strong>Account:</strong> A unique account created for you to access our Service or parts of our Service.</li>
              
              <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
              
              <li><strong>Company:</strong> Referred to as either "the Company", "We", "Us", or "Our" in this Agreement, refers to FrontenLab.</li>
              
              <li><strong>Cookies:</strong> Small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
              
              <li><strong>Country:</strong> Refers to Tamil Nadu, India.</li>
              
              <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
              
              <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
              
              <li><strong>Service:</strong> Refers to the Website.</li>
              
              <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
              
              <li><strong>Third-party Social Media Service:</strong> Any website or any social network website through which a user can log in or create an account to use the Service.</li>
              
              <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              
              <li><strong>Website:</strong> Refers to FrontenLab, accessible from <a href="https://www.frontenlab.com">https://www.frontenlab.com</a>.</li>
              
              <li><strong>You:</strong> The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2>Types of Data Collected</h2>

            <h3>Personal Data</h3>

            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

            <ul>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>

            <h3>Usage Data</h3>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <h3>Information from Third-Party Social Media Services</h3>
            <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
            <ul>
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>
            
            <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
            <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>

            <h3>Tracking Technologies and Cookies</h3>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>

            <ul>
              <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
              <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>

            <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>

            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

            <h2>Necessary / Essential Cookies</h2>
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>

            <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li><strong>To provide and maintain our Service:</strong> Including monitoring the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> Managing your registration as a user and providing access to functionalities available to registered users.</li>
                <li><strong>For the performance of a contract:</strong> Developing, complying with, and undertaking purchase contracts or any other contracts through the Service.</li>
                <li><strong>To contact You:</strong> Using email, phone, SMS, or other electronic communication methods for updates or information related to functionalities, products, services, or security updates.</li>
                <li><strong>To provide You with news, special offers, and information:</strong> About similar goods, services, or events unless you opted out.</li>
                <li><strong>To manage Your requests:</strong> Attending to and managing your requests.</li>
                <li><strong>For business transfers:</strong> Evaluating or conducting mergers, sales, restructuring, or similar business transactions where personal data is among the assets transferred.</li>
                <li><strong>For other purposes:</strong> Data analysis, identifying trends, evaluating promotional campaigns, and improving services and user experience.</li>
            </ul>

            <p>
            We may share Your personal information in the following situations:</p>
            <ul>
                <li><strong>With Service Providers:</strong> To monitor, analyze the use of our Service, and contact you.</li>
                <li><strong>For business transfers:</strong> In connection with mergers, asset sales, or acquisitions.</li>
                <li><strong>With Affiliates:</strong> Sharing with parent companies, subsidiaries, joint venture partners, or companies under common control, with a requirement to honor this Privacy Policy.</li>
                <li><strong>With business partners:</strong> To offer certain products, services, or promotions.</li>
                <li><strong>With other users:</strong> Personal information shared in public areas or through Third-Party Social Media Services may be viewed and publicly distributed.</li>
                <li><strong>With Your consent:</strong> Disclosing personal information for any other purpose with your consent.</li>
            </ul>

            <h2>Retention of Your Personal Data</h2>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

            <h2>Transfer of Your Personal Data</h2>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
            <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

            <h2>Delete Your Personal Data</h2>

            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
            <p>Our Service may give You the ability to delete certain information about You from within the Service</p>
            <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
            <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

            <h2>Disclosure of Your Personal Data</h2>
            <h2>Business Transactions</h2>
            <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

            <h2>Law enforcement</h2>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

            <h3>Other legal requirements</h3>

            <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

            <ul>
              <li><strong>Comply with a legal obligation:</strong> Meeting legal requirements and obligations.</li>
              <li><strong>Protect and defend the rights or property of the Company:</strong> Safeguarding the company's interests.</li>
              <li><strong>Prevent or investigate possible wrongdoing in connection with the Service:</strong> Addressing potential issues or misconduct.</li>
              <li><strong>Protect the personal safety of Users of the Service or the public:</strong> Ensuring safety and security for users and the general public.</li>
              <li><strong>Protect against legal liability:</strong> Mitigating potential legal risks and liabilities.</li>
          </ul>

          <h2>Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2>Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>

          <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

          <h2>Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          <h2>Changes to this Privacy Policy</h2>

          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

          <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the 12-08-2024 date at the top of this Privacy Policy.</p>

          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By visiting this page on our website: https://frontenlab/contact-us</li>
          </ul>
        </div>
    </div>
  )
}

export default PrivacyPolicy;